// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbXFyKITxbGBjhRjeneVosyWmutpOJulk',
    appId: '1:853844292424:web:40defce2128827ad87f97d',
    messagingSenderId: '853844292424',
    projectId: 'finalfacescan',
    authDomain: 'finalfacescan.firebaseapp.com',
    storageBucket: 'finalfacescan.appspot.com',
    measurementId: 'G-VE2RHE0E6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJX_Nc13n0QiatKCyH52-6Icyk9fzvHI',
    appId: '1:853844292424:android:b0108ef5acbcf10287f97d',
    messagingSenderId: '853844292424',
    projectId: 'finalfacescan',
    storageBucket: 'finalfacescan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIOBPggXKoubI2dIFyf2jh5CNpUDAK094',
    appId: '1:853844292424:ios:968e1122e18da4db87f97d',
    messagingSenderId: '853844292424',
    projectId: 'finalfacescan',
    storageBucket: 'finalfacescan.appspot.com',
    androidClientId: '853844292424-julb18h5tptnp3pf8j9slgi3ds9u4bko.apps.googleusercontent.com',
    iosClientId: '853844292424-bsj6bfrkbia3de6v4oh9k7bohvu14ar3.apps.googleusercontent.com',
    iosBundleId: 'com.facefinal.scan.facefinalscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIOBPggXKoubI2dIFyf2jh5CNpUDAK094',
    appId: '1:853844292424:ios:4b99b199981e285287f97d',
    messagingSenderId: '853844292424',
    projectId: 'finalfacescan',
    storageBucket: 'finalfacescan.appspot.com',
    androidClientId: '853844292424-julb18h5tptnp3pf8j9slgi3ds9u4bko.apps.googleusercontent.com',
    iosClientId: '853844292424-425p0ob0vf9hc9f7np2fqm59692l8diq.apps.googleusercontent.com',
    iosBundleId: 'com.facefinal.scan.facefinalscan.RunnerTests',
  );
}
